const imagePath = {
logo: require("@/src/assets/logo.jpeg"),
chaf: require("@/src/assets/images/alhadj-chafiou.jpeg"),
chafsadi: require("@/src/assets/images/chafiou-sadiya.jpeg"),
sadi: require("@/src/assets/images/sadiya .jpeg"),
compass: require ("@/src/assets/images/compass-chafadia.png"),
pillars: require ("@/src/assets/images/5pillars-chafadia.jpeg"),
adha: require ("@/src/assets/images/adha-chafadia.jpeg"),
hijjah: require ("@/src/assets/images/dhul-hijjah chafadia.jpeg"),
islam1: require ("@/src/assets/images/islam-chafadia.jpeg"),
islam2: require ("@/src/assets/images/islam2-chafadia.jpeg"),
janazah: require ("@/src/assets/images/janazah-chafadia.jpeg"),
salah: require ("@/src/assets/images/salah-chafadia.jpeg"),
salah2: require ("@/src/assets/images/salah2-chafadia.jpeg"),
sawn: require ("@/src/assets/images/sawn-chafadia.jpeg"),
wudu: require ("@/src/assets/images/wudu-chafadia.jpeg"),
zakat: require ("@/src/assets/images/zakat-chafadia.jpeg"),
essensial1: require ("@/src/assets/images/essentials1.jpeg"),
essential2: require ("@/src/assets/sounds/essential2.mp4"),
essential3: require ("@/src/assets/sounds/essential3.mp4"),
essential4: require ("@/src/assets/sounds/essential4.mp4"),
essential5: require ("@/src/assets/sounds/essential5.mp4"),
ghusl1: require ("@/src/assets/images/ghusl-chafadia.jpeg"),
ghusl2: require ("@/src/assets/images/ghusl2-chafadia.jpeg"),
death: require ("@/src/assets/sounds/7-signs that death is near.mp4"),
fajr: require ("@/src/assets/sounds/after-fajr.mp4"),
marriage: require ("@/src/assets/sounds/Arrange-marriage.mp4"),
azkar: require ("@/src/assets/sounds/azkar.mp4"),
patience: require ("@/src/assets/sounds/be patient-Allah sees.mp4"),
anger: require ("@/src/assets/sounds/control-anger.mp4"),
beyond: require("@/src/assets/sounds/death-beyond muslim.mp4"),
intimacy: require ("@/src/assets/sounds/intimacy-marriage.mp4"),
grief: require("@/src/assets/sounds/loosing-lovedone.mp4"),
moment: require("@/src/assets/sounds/moment-everythingchanges.mp4"),
bond: require ("@/src/assets/sounds/sacred-bond.mp4"),
shroud: require ("@/src/assets/sounds/shrouding-deceased.mp4"),
love: require ("@/src/assets/sounds/successfull mariage.mp4"),
hajj: require ("@/src/assets/images/hajj-chafadia.jpeg"),
tafsir1: require ("@/src/assets/sounds/Quran_Tafseer_01_27_-_Mufti_Menk(0).mp4"),
tafsir2: require ("@/src/assets/sounds/Quran_Tafseer_02_27_-_Mufti_Menk(0).mp4"),
tafsir3: require ("@/src/assets/sounds/Quran_Tafseer_03_27_-_Mufti_Menk(0).mp4"),
tafsir4: require ("@/src/assets/sounds/Quran_Tafseer_04_27_-_Mufti_Menk(0).mp4"),
tafsir5: require ("@/src/assets/sounds/Quran_Tafseer_05_27_-_Mufti_Menk(0).mp4"),
tafsir6: require ("@/src/assets/sounds/Quran_Tafseer_06_27_-_Mufti_Menk(0).mp4"),
tafsir7: require ("@/src/assets/sounds/Quran_Tafseer_07_27_-_Mufti_Menk(0).mp4"),
tafsir8: require ("@/src/assets/sounds/Quran_Tafseer_08_27_-_Mufti_Menk(0).mp4"),
tafsir9: require ("@/src/assets/sounds/Quran_Tafseer_09_27_-_Mufti_Menk(0).mp4"),
tafsir10: require ("@/src/assets/sounds/Quran_Tafseer_10_27_-_Mufti_Menk(0).mp4"),
tafsir12: require ("@/src/assets/sounds/Quran_Tafseer_12_27_-_Mufti_Menk(0).mp4"),
tafsir13: require ("@/src/assets/sounds/Quran_Tafseer_13_27_-_Mufti_Menk(0).mp4"),
tafsir14: require ("@/src/assets/sounds/Quran_Tafseer_14_27_-_Mufti_Menk(0).mp4"),
tafsir15: require ("@/src/assets/sounds/Quran_Tafseer_15_27_-_Mufti_Menk(0).mp4"),
tafsir16: require ("@/src/assets/sounds/Quran_Tafseer_16_27_-_Mufti_Menk(0).mp4"),
tafsir17: require ("@/src/assets/sounds/Quran_Tafseer_17_27_-_Mufti_Menk(0).mp4"),
tafsir18: require ("@/src/assets/sounds/Quran_Tafseer_18_27_-_Mufti_Menk(0).mp4"),
tafsir19: require ("@/src/assets/sounds/Quran_Tafseer_19_27_-_Mufti_Menk(0).mp4"),
tafsir20: require ("@/src/assets/sounds/Quran_Tafseer_20_27_-_Mufti_Menk(0).mp4"),
tafsir21: require ("@/src/assets/sounds/Quran_Tafseer_21_27_-_Mufti_Menk(0).mp4"),
tafsir22: require ("@/src/assets/sounds/Quran_Tafseer_22_27_-_Mufti_Menk(0).mp4"),
tafsir23: require ("@/src/assets/sounds/Quran_Tafseer_23_27_-_Mufti_Menk(0).mp4"),
tafsir24: require ("@/src/assets/sounds/Quran_Tafseer_24_27_-_Mufti_Menk(0).mp4"),
tafsir25: require ("@/src/assets/sounds/Quran_Tafseer_25_27_-_Mufti_Menk(0).mp4"),
tafsir26: require ("@/src/assets/sounds/Quran_Tafseer_26_27_-_Mufti_Menk(0).mp4"),
tafsir27: require ("@/src/assets/sounds/Quran_Tafseer_27_27_-_Mufti_Menk(0).mp4"),
tawaf: require ("@/src/assets/images/tawaf.png"),
umrah1: require ("/src/assets/images/umrah-badal men.png"),
umrah2: require ("@/src/assets/images/umrah-badal women.png"),
umrah3: require ("@/src/assets/images/umrah-guide.png"),
hadj2: require ("@/src/assets/images/Hajj-Badal.png"),
sai: require  ("@/src/assets/images/sai.png"),
morning: require ("@/src/assets/images/morning-duas.png"),
arafah: require ("@/src/assets/images/arafah.png"),
menstraution: require ("@/src/assets/images/menstraution1.jpeg"),
menstrauation: require ("@/src/assets/images/menstraution2.jpeg"),



};

export default imagePath;
